/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GD;

import javax.swing.JOptionPane;

import dao.DAO_NhanVien;
import entity.NhanVien;

/**
 *
 * @author ngphu
 */
public class GD_LayLaiMatKhau extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form GD_DoiMatKhau
     */
    public GD_LayLaiMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlVien = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        lblSoDT = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtTenTaiKhoan = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        lblXacNhan = new javax.swing.JLabel();
        txtXacNhan = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlVien.setBackground(new java.awt.Color(204, 255, 255));

        pnlMain.setBackground(new java.awt.Color(0, 204, 255));

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(0, 0, 102));
        lblTieuDe.setText("LẤY LẠI MẬT KHẨU");

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(0, 0, 102));
        lblTenDangNhap.setText("Tên tài khoản");

        lblSoDT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSoDT.setForeground(new java.awt.Color(0, 0, 102));
        lblSoDT.setText("Số điện thoại");

        lblMatKhauMoi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMatKhauMoi.setForeground(new java.awt.Color(0, 0, 102));
        lblMatKhauMoi.setText("Mật khẩu mới");

        btnXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.setBorderPainted(false);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnXacNhanActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.setBorderPainted(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lblXacNhan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblXacNhan.setForeground(new java.awt.Color(0, 0, 102));
        lblXacNhan.setText("Xác nhận mật khẩu");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblTieuDe))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTenDangNhap)
                                    .addComponent(lblSoDT))
                                .addGap(53, 53, 53)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(lblMatKhauMoi)
                                        .addGap(51, 51, 51)
                                        .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(lblXacNhan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlMainLayout.createSequentialGroup()
                                                .addComponent(btnXacNhan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtXacNhan))))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe)
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenDangNhap)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoDT)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhauMoi)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXacNhan)
                    .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVienLayout = new javax.swing.GroupLayout(pnlVien);
        pnlVien.setLayout(pnlVienLayout);
        pnlVienLayout.setHorizontalGroup(
            pnlVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVienLayout.setVerticalGroup(
            pnlVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold> 
    
    @SuppressWarnings("deprecation")
	public boolean layLaiMatKhau() throws Exception {
    	String tenTK,soDT,matKhauMoi,xacNhan;
    	if(kiemTraDuLieuRong()) {
    		tenTK =	txtTenTaiKhoan.getText().trim();
    		soDT = txtSoDT.getText().trim();
    		matKhauMoi = txtMatKhauMoi.getText();
    		xacNhan = txtXacNhan.getText();
    		NhanVien nhanVien = DAO_NhanVien.timNVTheoMa(tenTK);
    		
    		if(nhanVien.getMaNV()!=null) {
				if(soDT.equalsIgnoreCase(nhanVien.getSoDT())) {
					if(!nhanVien.getMatKhau().equalsIgnoreCase(matKhauMoi)) {
						if(matKhauMoi.equalsIgnoreCase(xacNhan)) {
							DAO_NhanVien.capNhatPass(nhanVien, matKhauMoi);
							JOptionPane.showMessageDialog(rootPane, "Lấy lại mật khẩu thành công");
							return true;
						}
						else{
							JOptionPane.showMessageDialog(rootPane, "Xác nhận mật khẩu không khớp với mật khẩu mới");
						}
					}
					else {
						JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới không được trùng với mật khẩu cũ!");
					}
				}else {
					JOptionPane.showMessageDialog(rootPane, "Số điện thoại không đúng");
				}
			}
			else {
				JOptionPane.showMessageDialog(rootPane, "Tên tài khoản không đúng");
			}
		}
    	return false;
    }
    
    public boolean kiemTraDuLieuRong() {
		String tenTK=txtTenTaiKhoan.getText().trim();
		String soDT = txtSoDT.getText().trim();
		@SuppressWarnings("deprecation")
		String matKhauMoi=txtMatKhauMoi.getText().trim();
		@SuppressWarnings("deprecation")
		String xacNhan = txtXacNhan.getText().trim();
		if (tenTK.trim().length() <= 0) { 
				JOptionPane.showMessageDialog(this, "Tài khoản không được để trống");
					return false;
		}
		if (soDT.trim().length() <= 0) { 
			JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống");
				return false;
		}
		if (matKhauMoi.trim().length() <= 0) { 
			JOptionPane.showMessageDialog(this, "Mật khẩu mới không được để trống");
				return false;
		}
		
		if (xacNhan.trim().length() <= 0) { 
			JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không được để trống");
				return false;
		}		
		return true;
    }

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                           
        // TODO add your handling code here:
    	if(layLaiMatKhau()) {
    		this.setVisible(false);
    	}
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_LayLaiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_LayLaiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXacNhan;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlVien;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JPasswordField txtXacNhan;
    // End of variables declaration                   
}
