/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GD;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import dao.DAO_ChucVu;
import dao.DAO_NhanVien;
import entity.ChucVu;
import entity.NhanVien;

/**
 *
 * @author ngphu
 */
public class GD_ThongTinNhanVien extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(".//images//ktv_logo.PNG"));

    public GD_ThongTinNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                     
    private void initComponents() {

        pnlVien = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblMaNV = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTenNV = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblSoCMND = new javax.swing.JLabel();
        lblSoDT = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        cbxGioiTinh = new javax.swing.JComboBox<>();
        txtChucVu = new javax.swing.JTextField();
        txtNgayVaoLam = new javax.swing.JTextField();
        txtSoCMND = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        btnDoiPass = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        setIconImage(icon.getImage());

        pnlVien.setBackground(new java.awt.Color(204, 255, 255));

        pnlMain.setBackground(new java.awt.Color(0, 204, 255));

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(0, 0, 102));
        lblTieuDe.setText("THÔNG TIN CÁ NHÂN");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatarNV.png"))); // NOI18N

        txtMaNV.setEditable(false);
        txtMaNV.setBackground(new java.awt.Color(204, 204, 204));
        txtMaNV.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblMaNV.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(0, 0, 102));
        lblMaNV.setText("Mã NV");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTenNV.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(0, 0, 102));
        lblTenNV.setText("Tên NV");

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(0, 0, 102));
        lblNgaySinh.setText("Ngày sinh");

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(0, 0, 102));
        lblGioiTinh.setText("Giới tính");

        lblChucVu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(0, 0, 102));
        lblChucVu.setText("Chức vụ");

        lblNgayVaoLam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNgayVaoLam.setForeground(new java.awt.Color(0, 0, 102));
        lblNgayVaoLam.setText("Ngày vào làm");

        lblSoCMND.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSoCMND.setForeground(new java.awt.Color(0, 0, 102));
        lblSoCMND.setText("Số CMND");

        lblSoDT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSoDT.setForeground(new java.awt.Color(0, 0, 102));
        lblSoDT.setText("Số điện thoại");

        txtTenNV.setEditable(false);
        txtTenNV.setBackground(new java.awt.Color(204, 204, 204));

        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        txtChucVu.setEditable(false);
        txtChucVu.setBackground(new java.awt.Color(204, 204, 204));

        txtNgayVaoLam.setEditable(false);
        txtNgayVaoLam.setBackground(new java.awt.Color(204, 204, 204));

        btnDoiPass.setBackground(new java.awt.Color(255, 255, 255));
        btnDoiPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoiPass.setText("ĐỔI MẬT KHẨU");
        btnDoiPass.setBorderPainted(false);
        btnDoiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiPassActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ic_lamMoi_NV.png"))); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.setBorderPainted(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnCapNhatActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close-icon.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.setBorderPainted(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenNV)
                    .addComponent(lblGioiTinh)
                    .addComponent(lblChucVu)
                    .addComponent(lblSoCMND)
                    .addComponent(lblSoDT)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayVaoLam))
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDoiPass, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(txtSoCMND, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSoDT, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtChucVu, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNgayVaoLam)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgaySinh)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh)
                    .addComponent(cbxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChucVu)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayVaoLam)
                    .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoCMND)
                    .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoDT)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoiPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlMainLayout.createSequentialGroup()
                                        .addComponent(lblMaNV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addGap(182, 182, 182))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98))))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout pnlVienLayout = new javax.swing.GroupLayout(pnlVien);
        pnlVien.setLayout(pnlVienLayout);
        pnlVienLayout.setHorizontalGroup(
            pnlVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVienLayout.setVerticalGroup(
            pnlVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
        DocDuLieuVaoTextFiedTTNV();
    }// </editor-fold>                        

    public String getTenChucVu(String maCV) {
    	ArrayList<ChucVu> lstChucVu = DAO_ChucVu.getAllChucVu();
    	for (ChucVu cv : lstChucVu) {
    		if(cv.getMaCV().equalsIgnoreCase(maCV))
    			return cv.getTenCV();
    	}
    	return "";
    }
    
    public void DocDuLieuVaoTextFiedTTNV()
    {
    	NhanVien nv = DAO_NhanVien.getNVDangLogin();
		txtMaNV.setText(nv.getMaNV());
		txtTenNV.setText(nv.getTenNV());
		cbxGioiTinh.setSelectedItem(nv.getGioiTinh());
		SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
		txtNgaySinh.setText(sdf.format(nv.getNgaySinh()));
		txtChucVu.setText(getTenChucVu(nv.getChucVu().getMaCV()));
		txtSoCMND.setText(nv.getSoCMND());
		txtSoDT.setText(nv.getSoDT());
		txtNgayVaoLam.setText(sdf.format(nv.getNgayVaoLam()));
    }
    
    public boolean capNhatTT() throws Exception {
    	String maNV, tenNV, nvl, chucVu, maCV, gioiTinh, ns, soCMND, soDT;
    	Date ngaySinh, ngayVaolam;
    	if(kiemTraDuLieu()) {
    		maNV = txtMaNV.getText();
        	tenNV = txtTenNV.getText();
        	ns = txtNgaySinh.getText().trim();
        	ngaySinh = Date.valueOf(ns.substring(6)+"-"+ns.substring(3,5)+"-"+ns.substring(0,2));
        	nvl = txtNgayVaoLam.getText().trim();
        	ngayVaolam = Date.valueOf(nvl.substring(6)+"-"+nvl.substring(3,5)+"-"+nvl.substring(0,2));
        	gioiTinh = cbxGioiTinh.getSelectedItem()+"";
        	chucVu = txtChucVu.getText();
        	maCV = layMaCVTheoTen(chucVu);
        	soDT = txtSoDT.getText();
        	soCMND = txtSoCMND.getText();
        	
        	NhanVien nv = new NhanVien(maNV, tenNV, gioiTinh, soDT, soCMND, ngaySinh, new ChucVu(maCV), ngayVaolam, null);
        	if(!DAO_NhanVien.capNhatNV(nv)) {
        		JOptionPane.showMessageDialog(rootPane, "Cập nhật không thành công!");
        		return false;
        	}
        	JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công!");
        	
    	}
    	return true;
    }
    
    public String layMaCVTheoTen(String tenCV) {
    	ArrayList<ChucVu> listCV = DAO_ChucVu.getAllChucVu();
    	for (ChucVu cv : listCV) {
			if(tenCV.equalsIgnoreCase(cv.getTenCV()))
				return cv.getMaCV();
		}
    	return "";
    }
    
    public boolean kiemTraDuLieu() {
    	String ngaySinh=txtNgaySinh.getText().trim();
		String soCMND = txtSoCMND.getText().trim();
		String soDT = txtSoDT.getText().trim();
  		
  		if (ngaySinh.trim().length() > 0) {
			if (!(ngaySinh.matches("\\b(0?[1-9]|[12]\\d|3[01])[\\/\\-.](0?[1-9]|[12]\\d|3[01])[\\/\\-.](\\d{2}|\\d{4})\\b"))) {
				JOptionPane.showMessageDialog(this, "Ngày sinh có định dạng dd-MM-yyyy");
				return false;
			}
		} else {
			JOptionPane.showMessageDialog(this, "Ngày sinh không được để trống");
			return false;
		}
		
		if (soCMND.trim().length() > 0) {
			if (!(soCMND.matches("[0-9]{9}")) && !(soCMND.matches("[0-9]{12}"))) {
				JOptionPane.showMessageDialog(this, "CMND phải gồm 9 hoặc 12 số");
				return false;
			}
		} else {
			JOptionPane.showMessageDialog(this, "CMND không được để trống");
			return false;
		}
		if (soDT.trim().length() > 0) {
			if (!(soDT.matches("[0-9]{10}"))) {
				JOptionPane.showMessageDialog(this, "Số điện thoại phải gồm 10 số");
				return false;
			}
		} else {
			JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống");
			return false;
		}
		return true;
    }
    
    
    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {                                         
        GD_Chinh uiChinh = new GD_Chinh();
        uiChinh.setVisible(true);
    	this.setVisible(false);
    }                                        

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) throws Exception {                                           
        // TODO add your handling code here:
    	capNhatTT();
    }                                          

    private void btnDoiPassActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	GD_DoiMatKhau ui = new GD_DoiMatKhau();
    	this.setVisible(false);
    	ui.setVisible(true);
    	
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_ThongTinNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiPass;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbxGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration                   
}
